name: Build and deploy Node.js app to Azure Web App - bloggie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and build frontend
        run: |
          cd client
          npm install
          npm run build
      
      - name: Install backend dependencies
        run: |
          cd ../api
          npm install

      - name: Archive production artifacts
        run: |
          cd ..
          zip -r bloggie.zip client api -x "*/node_modules/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: bloggie.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: bloggie.zip

      - name: Deploy to Azure Web App - Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bloggie-api'
          slot-name: 'Production'
          package: bloggie.zip

      - name: Deploy to Azure Web App - Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bloggie-client'
          slot-name: 'Production'
          package: bloggie.zip
